config/routes.rb
# -*- encoding : utf-8 -*-
CINC::Application.routes.draw do
  root :to => "home#index"
  devise_for :users

  get  "admin/states_stats"
  get  "admin/index"
  get  "admin/add_student"
  get  "admin/students"
  get  "admin/student/log/:id", to: 'admin#student_log', as: 'admin_student_log'
  post "admin/update_table"
  post "admin/add_student"
  get  "admin/export_table"
  get  "admin/stats/(:type)", to: 'admin#stats', as: 'admin_stats'
end

app/models/ability.rb
# -*- encoding : utf-8 -*-
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/machine.rb
# -*- encoding : utf-8 -*-
class Machine < ActiveRecord::Base
  belongs_to :student
  has_many :machine_states
  has_many :states, :through => :machine_states
end

app/models/machine_state.rb
# -*- encoding : utf-8 -*-
class MachineState < ActiveRecord::Base
  belongs_to :state
  belongs_to :machine
end

app/models/role.rb
# -*- encoding : utf-8 -*-
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/state.rb
# -*- encoding : utf-8 -*-
class State < ActiveRecord::Base
  has_many :machine_states
  has_many :machines, :through => :machine_states
end

app/models/student.rb
# -*- encoding : utf-8 -*-
class Student < ActiveRecord::Base
  has_one :machine
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
# -*- encoding : utf-8 -*-
class AdminController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @students = Student.includes(:machine => [:machine_states, :states]).first(10)
  end

  def students
    # make the json for datatables
    if params['iDisplayStart'] and params['iDisplayLength'] then
      @students = Student.paginate(:page => params['iDisplayStart'], :per_page => params['iDisplayLength']).
                          includes(:machine => [:machine_states, :states])
    else
      @students = Student.all.includes(:machine => [:machine_states, :states])
    end

    if params['sSearch'] then
      @students.where('name LIKE ?', params['sSearch'])
    end

    if params['iSortingCols'] then
      @students.order('? DESC', params['iSortingCols'])
    end

    @json = {}
    @json['aaData'] = []
    @students.each { |stu|
                          # alumno, cuil, s/n, modelo, estado, razón
      @json['aaData'] << [stu.id, stu.name, stu.cuil, stu.machine.sn, stu.machine.model,
                            stu.machine.states.last.name, stu.machine.machine_states.last.reason]
    }
    render :json => @json
  end

  def student_log
    @student = Student.includes(:machine => [:machine_states, :states]).find(params[:id])
  end

  def states_stats
    @students = Student.all.includes(:machine => [:machine_states, :states])
    @states   = {}
    @students.each { |stu|
      state = stu.machine.states.last.name
      @states[state] = 0 if not @states[state]
      @states[state] += 1
    }
    render :json => @states
  end

  def update_table
    @student = Student.find(params[:row_id])

    case params[:column]
    when "1" # name
      @student.name = params[:value]
      @student.save!
    when "2" # cuil
      @student.cuil = params[:value]
      @student.save!
    when "3" # sn
      @machine = @student.machine
      @machine.sn = params[:value]
      @machine.save!
    when "4" # model
      @machine = @student.machine
      @machine.model = params[:value]
      @machine.save!
    when "5" # state
      @state = State.find_or_create_by(name: params[:value])
      @student.machine.states << @state
    when "6" # reason
      @reason = @student.machine.machine_states.last
      @reason.reason = params[:value]
      @reason.save!
    end

    if request.xhr? then
      render :text => params[:value]
    end
  end

  def add_student
    if request.post?
      @student = Student.new
      @student.name = params[:student][:name]
      @student.cuil = params[:student][:cuil]
      @student.save!
      @student.machine = Machine.create(:sn => params[:student][:sn], :model => params[:student][:model])
      @machine = @student.machine
      @state = State.find_or_create_by(name: params[:student][:state])
      @machine.states << @state
      @reason = @machine.machine_states.last
      @reason.reason = params[:student][:reason]
      @reason.save!

      redirect_to admin_index_path
    end
  end

  def export_table
    require 'csv'
    @students = Student.all.includes(:machine => [:machine_states, :states])

    filename = "alumnos_#{Date.today.strftime('%d%b%y')}.csv"
    csv_data = CSV.generate do |csv|
      # head
      csv << ['ID', 'Alumno', 'CUIL', 'Número de Serie', 'Modelo', 'Estado Actual', 'Razón']
      # body
      @students.each do |stu|
        csv << [stu.id, stu.name, stu.cuil, stu.machine.sn, stu.machine.model,
                  stu.machine.states.last.name, stu.machine.machine_states.last.reason]
      end
    end

    send_data csv_data,
                :type => 'text/csv; charset=UTF-8; header=present',
                :disposition => "attachment; filename=#{filename}"
  end

  def stats
    if request.format == :json
      case params[:type]
      when 'usage'
        @usage = MachineState.all.group_by{ |item| item.send(:created_at).beginning_of_day }.
                  map { |v| [v.first, v.last.count] }
        render :json => @usage
      when 'students'
        @students = Student.all.includes(:machine => [:machine_states, :states])
        @states   = {}
        @students.each { |stu|
          state = stu.machine.states.last.name
          @states[state] = 0 if not @states[state]
          @states[state] += 1
        }
        render :json => @states
      when 'students_states'
        @changes = MachineState.select(:updated_at).load.
                    group_by{|ms| ms.updated_at.beginning_of_day}.map{ |ms| [ms.first, ms.last.count]}
        render :json => @changes
      end
    end
  end
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  layout :layout_by_resource
  before_action :gon_vars

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  def layout_by_resource
    if devise_controller?
      "login"
    else
      "application"
    end
  end

  def gon_vars
    gon.update_table          = admin_update_table_path
    gon.students_url          = admin_students_path('json')
    gon.admin_student_log_url = admin_student_log_path('replace_me')
    gon.action                = action_name
  end

end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
    redirect_to admin_index_path
  end
end

app/helpers/admin_helper.rb
# -*- encoding : utf-8 -*-
module AdminHelper
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/views/admin/add_student.html.haml
%h2 Añadir Alumno
%center
  %div{style: 'width: 500px'}
    = form_tag(admin_add_student_path, method: 'POST', class: 'form-horizontal') do
      .form-group
        %div.col-lg-4
          %label.control-label.col-lg-4{:for => "name"} Nombre
        %div.col-lg-8
          %input#name.form-control{:type => "text", :name => 'student[name]'}/
      .form-group
        %div.col-lg-4
          %label.control-label.col-lg-4{:for => "cuil"} CUIL
        %div.col-lg-8
          %input#cuil.form-control{:type => "text", :name => 'student[cuil]'}/
      .form-group
        %div.col-lg-4
          %label.control-label.col-lg-4{:for => "sn"} S/N
        %div.col-lg-8
          %input#sn.form-control{:type => "text", :name => 'student[sn]'}/
      .form-group
        %div.col-lg-4
          %label.control-label.col-lg-4{:for => "model"} Modelo
        %div.col-lg-8
          %input#model.form-control{:type => "text", :name => 'student[model]'}/
      .form-group
        %div.col-lg-4
          %label.control-label.col-lg-4{:for => "state"} Estado
        %div.col-lg-8
          %input#state.form-control{:type => "text", :value => 'ingresada', :name => 'student[state]'}/
      .form-group
        %div.col-lg-4
          %label.control-label.col-lg-4{:for => "reason"} Razón
        %div.col-lg-8
          %input#reason.form-control{:type => "text", :name => 'student[reason]'}/
      .form-group
        %div.col-lg-12
          %center
            %button.btn.btn-primary Añadir

app/views/admin/index.html.haml
.col-lg-12
  %h2 Panel de Administración
  = pie_chart admin_states_stats_path('json'), height: '150px'

%table.datatable{:name => "students"}
  %thead
    %tr
      %th ID
      %th Alumno
      %th CUIL
      %th Número de Serie
      %th Modelo
      %th Estado Actual
      %th Razón
  %tbody
    - @students.each do |student|
      %tr{:id => student.id}
        %td{:id => 'id', :width => '5%'}
          = student.id
        %td{:id => 'name'}
          = student.name
        %td{:id => 'cuil'}
          = student.cuil
        %td{:id => 'sn'}
          = student.machine.sn
        %td{:id => 'model'}
          = student.machine.model
        %td{:id => 'state'}
          = student.machine.machine_states.last.state.name
        %td{:id => 'reason'}
          = student.machine.machine_states.last.reason
%br
%br
%br

%div{:style => 'text-align: right'}
  = link_to "Exportar", admin_export_table_path('csv')

app/views/admin/stats.html.haml
.col-lg-12
  %h1 Estadísticas

  %center
    %h2 Uso de la Aplicación
  = area_chart admin_stats_path('usage', 'json'), height: '300px'

  %center
    %h2 Estados Actuales
  = pie_chart admin_stats_path('students', 'json'), height: '500px'

  %center
    %h2 Total de Cambio de Estados Por Día
  = area_chart admin_stats_path('students_states', 'json')

app/views/admin/student_log.html.haml
.col-lg-12
  %h2
    Registro de 
    = @student.name
  %p
    %ul
      %li
        %p
          CUIL:
          = @student.cuil
      %li
        %p
          Estado Actual: 
          %em
            = @student.machine.states.last.name
      %li
        %p
          Razón del Estado:
          %br
          «
          = @student.machine.machine_states.last.reason
          »

      %li
        %p
          Registro de Estados
          %ul
            - @student.machine.machine_states.order('id DESC').each do |stu|
              %li
                = stu.created_at.strftime('[%d/%m/%Y]')
                = (stu.state.name || 'Estado sin nombre') << ':'
                %em
                  «
                  = stu.reason || 'Sin descripción'
                  »

app/views/home/index.html.haml
%h1 TODO: ¡hay que cambiar esto!

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
/ = link_to "Cinc", root_path, :class => 'brand'
/ %ul.nav
/   - if user_signed_in?
/     %li
/       = link_to 'Logout', destroy_user_session_path, :method=>'delete'
/   - else
/     %li
/       = link_to 'Login', new_user_session_path
/   - if user_signed_in?
/     %li
/       = link_to 'Edit account', edit_user_registration_path
/     - if current_user.has_role? :admin
/       %li
/         = link_to 'Admin', users_path
/   - else
/     %li
/       = link_to 'Sign up', new_user_registration_path


%li.accordion-group
  %a.accordion-toggle{"data-parent" => "#menu", "data-target" => "#dashboard-nav", "data-toggle" => "collapse", :href => admin_index_path}
    %i.icon-dashboard
    Panel de Admin
%li.accordion-group
  %a.accordion-toggle{"data-parent" => "#menu", "data-target" => "#dashboard-nav", "data-toggle" => "collapse", :href => admin_add_student_path}
    %i.icon-file
    Añadir Alumno
%li.accordion-group
  %a.accordion-toggle{"data-parent" => "#menu", "data-target" => "#dashboard-nav", "data-toggle" => "collapse", :href => admin_stats_path}
    %i.icon-bar-chart
    Estadísticas

app/views/layouts/application.html.haml
!!!
%html{:lang => "es"}
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "CINC"
      %meta{:charset => "UTF-8"}/
      %meta{:content => content_for?(:description) ? yield(:description) : "Cinc", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        /[if lt IE 8]
          = stylesheet_link_tag "font-awesome-ie7.min.css", media: "all"
        = javascript_include_tag :modernizr
        = csrf_meta_tags
        = yield(:head)
        = include_gon(watch: true)
        = javascript_include_tag "application"
        = javascript_include_tag "//www.google.com/jsapi", "chartkick"
  %body{:class => "#{controller_name} #{action_name}"}
    #wrap
      #top
        / .navbar
        %nav.navbar.navbar-inverse.navbar-static-top
          / Brand and toggle get grouped for better mobile display
          %header.navbar-header
            %a.navbar-brand{:href => "index.html"}
              = image_tag 'logo.png'
          .topnav
            .btn-toolbar
              .btn-group
                %a#changeSidebarPos.btn.btn-success.btn-sm{"data-original-title" => "Modo Ancho", "data-placement" => "bottom", "data-toggle" => "tooltip"}
                  %i.icon-resize-horizontal
              .btn-group
                %a.btn.btn-default.btn-sm{"data-original-title" => "Backups", "data-placement" => "bottom", "data-toggle" => "tooltip", href: "#"}
                  %i.icon-file
              .btn-group
                = link_to(destroy_user_session_path, {"data-original-title" => "Cerrar Sesión", "data-placement" => "bottom", "data-toggle" => "tooltip", "class" => "btn btn-metis-1 btn-sm", "data-no-turbolink" => true}) do
                  %i.icon-off
          
        / /.navbar
        / header.head
        %header.head
          .search-bar
            %form.main-search
              / TODO: hacerlo funcionar :-P
              .input-group
                %input.input-small.form-control{placeholder: "Buscar alumno ...", type: "text"}/
                %span.input-group-btn
                  %button.btn.btn-default.btn-sm{type: "button"}
                    %i.icon-search

          .main-bar
            %h3
              %i.icon-home
              CINC - Conectar Igualdad Netbook Manager
          / /.main-bar
        / end header.head
      / /#top
      #left
        %ul#menu.accordion.collapse
          %li.nav-header Menú
          %li.nav-divider
          = render :partial => 'layouts/navigation'
        / /#menu
      / /#left
      #content
        .outer
          .inner
            =yield
          / end .inner
        / end .outer
      / end #content
    / /#wrap
    #footer
      %p
        2013
        = link_to "CINC", "http://github.com/fermuch/CINC"

app/views/layouts/login.html.haml
!!!
%html{lang: "es"}
  %head
    %meta{charset: "UTF-8"}/
    %title Iniciar Sesión
    = csrf_meta_tags
    = yield(:head)
    = stylesheet_link_tag('bootstrap_and_overrides')
    = stylesheet_link_tag('/login')
  %body
    .container
      #signin
        .text-center
          = image_tag "logo.png"
          - flash.each do |msg,text|
            %br
            %li.label.label-danger
              = text
        .tab-content
          =yield
    / /container